"""Planner giornaliero: application service (scoring, constraints, capacity)."""

from src.planner.calibration import factor_for, observe, observe_all
from src.planner.decisions import (
    CONSTRAINED,
    DEFERRED,
    NOT_SCHEDULED,
    SCHEDULED,
    PlanningDecision,
    decide,
    primary_reason,
    refine_with_schedule,
)
from src.planner.diagnostics import diagnose
from src.planner.feedback import feedback
from src.planner.models import (
    BLOCKED_BUSY,
    BLOCKED_CAPACITY,
    BLOCKED_DEADLINE,
    BLOCKED_DURATION,
    BLOCKED_KINDS,
    BLOCKED_TASKS,
    BLOCKED_USER_SKIP,
    BLOCKED_WINDOW,
    DETAIL_KEYS,
    DIAG_CONSTRAINED,
    DIAG_KINDS,
    DIAG_NO_AVAIL,
    DIAG_OVERFLOW,
    DayPlan,
    ExecutionFeedback,
    FixedEvent,
    PlanAlternative,
    PlanDiagnostic,
    PlanItem,
    PlanningRequest,
    PlanningResult,
    ScheduledDayPlan,
    ScheduledItem,
    TaskView,
    TimeWindow,
    todo_to_task,
)
from src.planner.narrative import explain_decision, explain_proposed, story_keys
from src.planner.replan import (
    ADDED,
    DROPPED,
    KEPT,
    MOVED,
    ReplanMove,
    ReplanProposal,
    replan,
)
from src.planner.scheduler import deadlines_for, events_to_busy, schedule
from src.planner.service import Planner, plan

__all__ = [
    "ADDED",
    "BLOCKED_BUSY",
    "BLOCKED_CAPACITY",
    "BLOCKED_DEADLINE",
    "BLOCKED_DURATION",
    "BLOCKED_KINDS",
    "BLOCKED_TASKS",
    "BLOCKED_USER_SKIP",
    "BLOCKED_WINDOW",
    "CONSTRAINED",
    "DEFERRED",
    "DETAIL_KEYS",
    "DIAG_CONSTRAINED",
    "DIAG_KINDS",
    "DIAG_NO_AVAIL",
    "DIAG_OVERFLOW",
    "DROPPED",
    "DayPlan",
    "ExecutionFeedback",
    "FixedEvent",
    "KEPT",
    "MOVED",
    "NOT_SCHEDULED",
    "PlanAlternative",
    "PlanItem",
    "PlanDiagnostic",
    "Planner",
    "PlanningDecision",
    "PlanningRequest",
    "PlanningResult",
    "ReplanMove",
    "ReplanProposal",
    "SCHEDULED",
    "ScheduledDayPlan",
    "ScheduledItem",
    "TaskView",
    "TimeWindow",
    "decide",
    "deadlines_for",
    "diagnose",
    "events_to_busy",
    "explain_decision",
    "explain_proposed",
    "factor_for",
    "feedback",
    "observe",
    "observe_all",
    "plan",
    "primary_reason",
    "refine_with_schedule",
    "replan",
    "schedule",
    "story_keys",
    "todo_to_task",
]
